version: "3"

services:
  ph8:
    build: 
      context: .
      target: development
    env_file: .env
    ports: 
      - ${HTTP_PORT}:${HTTP_PORT}
      - 9229:9229
    restart: always
    volumes: 
      - ./src:/home/deno/src
      - ./data:/home/deno/data
