name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: thezanke/ph8/ph8
          tag_with_ref: true
